### ISSUE TITLE
iCloud 2-Step support

### ISSUE THREAD

**Issue by mulot** [JanHalozan/iTunesConnectAnalytics#27]
Cannot login if iCloud account uses 2-Step verification

**Comment by JanHalozan** [comment]
Yes, as you can imagine 2-Step verification requires inputting a code which changes every so often and the access cookie expires eventually so long running operations aren't possible without disabling two factor auth. It is possible to add it but I'm currently unavailable to do so. If you can do it you can submit a PR and we can start supporting it.

That would mean every time iTunesConnectAnalytics would get launched it would have to pass the 2FA code when performing login.

There is a workaround though. You can create a separate user without 2FA and use a reaaaaaaaly long password in order to increase security.

**Comment by mulot** [comment]
Thank you Jan. 

I did not think about the workaround you mentioned. It’s OK for me.
